collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    source: demo2.sandbox127.opentlc.com
    version: 0.9.3
  #  source: https://demo2.sandbox127.opentlc.com
